### ISSUE TITLE
when okx is support fot the example method execute？

### ISSUE THREAD

**Issue by rzyaly** [Nouzan/exc#26]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/19159208/200545277-bf59677c-b11e-4616-90c1-862f11b13784.png">
Waiting,hahaha

**Comment by Nouzan** [comment]
We haven't implemented `SubscribeOrdersService` for `Okx` yet, that is what blocks the support of `Okx` in the `exc-trading` example. We may implement it by the end of the week, along with the release of `v0.5.1`.

**Comment by rzyaly** [comment]
Ok,I'm looking forward to this. EXC is really an excellent project
