### ISSUE TITLE
Something wrong happen when i use PlaceOrderOptions to place a long side limit order.

### ISSUE THREAD

**Issue by rzyaly** [Nouzan/exc#31]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/19159208/202601966-3844270d-f4ec-4068-bdd6-f59ab40eb624.png">

It means i can not choose the position side.So i had to follow the demo such as binance_trading_directly.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/19159208/202602569-26fab25c-6170-4991-970b-e16600bfeffa.png">

**Comment by Nouzan** [comment]
No, you can't choose the position side in the `exc` layer. The `exc` abstraction layer is designed to only support the `buy/sell` mode for maximum compatibility.

In some cases, we find that the `long/short` mode will mess things up. So we calculate and manage the positions ourselves by using [Nouzan/positions](https://github.com/Nouzan/positions). You can do the same thing that the `long/short` mode intends to do by storing the order updates into two `Position` variables according to the "position sides" they belong to.

Or, you can always use the `exc_binance` APIs directly, which should be also well-supported.

**Comment by Nouzan** [comment]
And `PlaceOrderOptions` is an experimental feature, only a few attributes of the `OKX` API is supported. Maybe I should mention this in the document. Sorry.

**Comment by rzyaly** [comment]
Maybe I should use two accounts to solve this problom.
