### ISSUE TITLE
Some standard libraries may have performance issues, such as std::collections::HashMap

### ISSUE THREAD

**Issue by rzyaly** [Nouzan/exc#33]
Maybe it's a good idea choice  hashbrown::HashMap instead of std::collections::HashMap。

**Comment by Nouzan** [comment]
According to the note from [hashbrown](https://crates.io/crates/hashbrown), `hashbrown::HashMap` has already been the implementation of `std::collections::HashMap` since `Rust 1.36`. But thank you for advice, and if you find any other performance issues, feel free to ask me again. 😊
