### ISSUE TITLE
Advice from a pragmatist

### ISSUE THREAD

**Issue by rzyaly** [Nouzan/exc#34]
Preamble, I think this project does a really good job of abstracting the exchange interface, and I've been doing some promotion these days
<img width="961" alt="image" src="https://user-images.githubusercontent.com/19159208/202900294-c84fae2b-6b9e-4a0f-8c69-7fab8a35d867.png">
However, from my previous long-term experience, the current demo way may not be enough.Sometimes it is necessary to implement a simple strategy based on a single transaction.
For example, many times the use of multiple exchanges and multiple accounts is very common. I need to dynamically add, enable, or disable accounts through ws, rpc, http, or even just listening for configuration file changes.
I have been using java to implement trading systems and am now switching to rust,Below are some of my current plans.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/19159208/202900671-93e7564d-c9f5-48be-bfd6-c8e686dd8840.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/19159208/202900722-10ef5d44-6cd7-4c86-a77b-69ba8ac6958c.png">
Hope to progress with you,HiHi.

**Comment by rzyaly** [comment]
when i need to cache the Exc<Binance,Request> ,something wrong happen. This seems a little difficult to solve the problem  for a beginner like me.
<img width="998" alt="image" src="https://user-images.githubusercontent.com/19159208/202900795-27d58521-bc76-4b3b-ab09-6abb48e38ea2.png">

**Comment by Nouzan** [comment]
The problem is that `ServiceExt::ready` method requires a mutable reference to call. And since `HashMap` has been wrapped in a `Mutex`, you should be able to call `HashMap::get_mut` to get the required mutable reference after locking.

Besides that, you can clone `Okx` and `Binance` cheaply (they all use [`tower::buffer::Buffer`](https://docs.rs/tower/latest/tower/buffer/index.html) internally, which makes `Exc` also a `Clone`). So maybe you can just clone it before calling `ready` or some other "mutable" methods.

**Comment by rzyaly** [comment]
Ok, let me have a try.

**Comment by Nouzan** [comment]
And thank you for the promotion, I feel honored.

Recently, I am working on combining `exc`, `indicator` and `positions` all together to make them a trading framework. We will have more and better examples until then.

**Comment by Nouzan** [comment]
Maybe [`tower::discover`](https://docs.rs/tower/latest/tower/discover/index.html) will be helpful.

**Comment by rzyaly** [comment]
> 

It seems to be working when i use `HashMap::get_mut`.
