### ISSUE TITLE
can you give me a demo for binance trading example can Take Profit Stop Loss?

### ISSUE THREAD

**Issue by jackbbhua** [Nouzan/exc#50]
can you give me a demo for binance trading example can Take Profit Stop Loss?  thanks in advance.

**Comment by Nouzan** [comment]
In `exc`, we prefer to do it manually, therefore we haven't add support to the `stop-loss/take-profit` APIs.

To setup a stop-loss / take-profit condition manually, the following approach may be helpful:
- Firstly, you need to determine your current position status. You can do this in a per-order way with `CheckOrderService`. 
- Secondly, you should subscribe to the `TickerStream`s of the instruments of your positions.   Every time a new `Ticker` arrives, you can calculate the unrealized profit and loss of each orders to see if you need to perform a stop-loss / take-profit.

We have also provided utils for these kinds of calculations:
- For managing the positions status, see https://docs.rs/positions/latest/positions/instrument/struct.Instrument.html#method.position .
- And for calculating the unrealized profit and loss, see https://docs.rs/positions/latest/positions/position/struct.Position.html#method.closed.

**Comment by jackbbhua** [comment]
thank you in advance.

**Comment by Nouzan** [comment]
I think I have answered your question, so I am going to close this issue. Feel free to reopen if you need more explanation.
