### ISSUE TITLE
Why delete `FetchLastCandlesService` in main branches

### ISSUE THREAD

**Issue by rise0chen** [Nouzan/exc#53]
I want to wrap the interface, like this:
```rust
impl<C, Req> Exchange<C, Req>
where
    Exc<C, Req>: FetchCandlesService,
{
}
```
but, OKX not implement `FetchCandlesService`.
OKX had implement `QueryLastCandles`, but I can't find `FetchLastCandlesService` in main branches.

**Comment by Nouzan** [comment]
The implementation is still there, but not implemented directly. You can use `ExcExt::into_fetch_candles_backward_with_bound` to convert a `Exc<impl Request<QueryLastCandles>>` into a `FetchCandlesService`. You can find the usage example [here](https://github.com/Nouzan/exc/blob/main/examples/examples/okx_candle.rs).

**Comment by rise0chen** [comment]
Ok， I can use `ExcService<QueryLastCandles>` to constraint `Exc<C, Req>`
