### ISSUE TITLE
Sometimes `QueryLastCandles` takes a long time (2m 11s)

### ISSUE THREAD

**Issue by rise0chen** [Nouzan/exc#56]
```rust
impl<C, Req> Exchange<C, Req>
where
    Exc<C, Req>: ExcService<QueryLastCandles>,
{
    pub async fn get_price(&mut self, period: Period, num: usize) -> anyhow::Result<Vec<Decimal>> {
        let range = ..;
        let req = QueryLastCandles::new(&self.inst, period, range, num);
        let sub = (&mut self.public_exc).oneshot(req).await?;
        let data = sub.filter_map(|x| async { x.ok().map(|x|x.close) }).collect().await;
        Ok(data)
    }
}
```

Sometimes it takes a long time(2m 11s), but in most cases it only takes a short time(0.7s).

Do you know what causes it to take a long time?

**Comment by Nouzan** [comment]
What are the arguments you used within the above method?

**Comment by rise0chen** [comment]
```rust
let history = self.exchange.get_price(Period::minutes(UtcOffset::UTC, 1), 100).await.unwrap();
let price = self.exchange.get_price(Period::seconds(UtcOffset::UTC, 1), 1).await;
```
It may be caused by network fluctuations.

**Comment by rise0chen** [comment]
Can we set timeout for http?

**Comment by Nouzan** [comment]
You can set timeout at request level.

**Comment by rise0chen** [comment]
use [tokio](https://docs.rs/tokio/latest/tokio/index.html)::[time](https://docs.rs/tokio/latest/tokio/time/index.html)::[timeout](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html#) ?

**Comment by Nouzan** [comment]
Yes, or you can use [`TimeoutLayer`](https://docs.rs/tower/latest/tower/timeout/struct.TimeoutLayer.html) if you are familiar with  `tower`.
