### ISSUE TITLE
subscribe_tickers can't recv any data on binance

### ISSUE THREAD

**Issue by rise0chen** [Nouzan/exc#61]
The program is blocked on `tickers.next().await` in https://github.com/Nouzan/exc/blob/main/examples/examples/binance_ticker.rs

**Comment by rise0chen** [comment]
blocked on https://github.com/Nouzan/exc/blob/430a95fed042a55ad44b3359207367fd0134fdf3/exc/src/util/subscribe_tickers.rs#LL122C29-L122C29

```
export ENDPOINT=binance-u
export INST=BTCUSDT
```
And, example `binance_trade_bid_ask` is work

**Comment by Nouzan** [comment]
The correct instrument format is all lowercase and without separators for *Binance*, like `btcusdt`. But it is a problem that it won't throw an error when the format is wrong.

**Comment by Nouzan** [comment]
And you can also try the `InstrumentsLayer` which will create a conversion layer that can convert between the standard instrument format and the exchange-defined format. You can check the examples for [binance](https://github.com/Nouzan/exc/blob/main/examples/examples/binance_instruments.rs) and [okx](https://github.com/Nouzan/exc/blob/main/examples/examples/okx_instruments.rs). Though there are too many details and not easy to use for now, not until I define the `ToExchange` trait.

**Comment by rise0chen** [comment]
ok, `export INST=btcusdt` is work
