### ISSUE TITLE
into_fetch_candles_forward  method not found 

### ISSUE THREAD

**Issue by lijiachang** [Nouzan/exc#97]
examples/examples
├── binance_candle.rs
├── binance_rate_limit.rs
├── box_exc_service.rs

These three files have the same error：

error[E0599]: no method named `into_fetch_candles_forward` found for struct `Exc` in the current scope
  --> examples/examples/binance_rate_limit.rs:11:10
   |
8  |       let mut binance = Binance::usd_margin_futures()
   |  _______________________-
9  | |         .connect_exc()
10 | |         .into_rate_limited(70, Duration::from_secs(60))
11 | |         .into_fetch_candles_forward(1500);
   | |         -^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `Exc<RateLimit<IntoService<Binance, Request>>, Request>`
   | |_________|
   | 

  --> examples/examples/box_exc_service.rs:42:46
   |
42 |             candle: Box::new(binance.clone().into_fetch_candles_forward(1000)),
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `Exc<Binance, Request>`

**Comment by Nouzan** [comment]
Thank you for pointing out, but I can't reproduce it. Cloud you please provide more information, such as the commit hash of the `exc`, Rust version, and the command being executed?

**Comment by lijiachang** [comment]
Hi Nouzan，thanks for your reply

exc is the last：6abd55ace1080a6c0c781ed575481bda0d30e343
rust version：rustc 1.77.2 (25ef9e3d8 2024-04-09)
example version?:   Compiling examples v0.7.3-nightly 

execute aommand：cargo run  --example binance_rate_limit


**and total command info：**
➜  examples git:(main) ✗ pwd    
/Users/lijiachang/code/rust/exc/examples
➜  examples git:(main) ✗ 
➜  examples git:(main) ✗ cargo run  --example binance_rate_limit
warning: fields `6`, `7`, `8`, `9`, `10`, and `11` are never read
  --> exc-binance/src/http/response/candle.rs:24:5
   |
10 | pub struct Candle(
   |            ------ fields in this struct
...
24 |     pub(crate) i64,
   |     ^^^^^^^^^^^^^^
25 |     /// Volume in quote.
26 |     pub(crate) Decimal,
   |     ^^^^^^^^^^^^^^^^^^
27 |     /// The number of trades.
28 |     pub(crate) usize,
   |     ^^^^^^^^^^^^^^^^
29 |     /// Taker volume.
30 |     pub(crate) Decimal,
   |     ^^^^^^^^^^^^^^^^^^
31 |     /// Taker volume in quote.
32 |     pub(crate) Decimal,
   |     ^^^^^^^^^^^^^^^^^^
33 |     /// Ignore.
34 |     serde_json::Value,
   |     ^^^^^^^^^^^^^^^^^
   |
   = note: `Candle` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default
help: consider changing the fields to be of unit type to suppress this warning while preserving the field numbering, or remove the fields
   |
24 ~     (),
25 |     /// Volume in quote.
26 ~     (),
27 |     /// The number of trades.
28 ~     (),
29 |     /// Taker volume.
30 ~     (),
31 |     /// Taker volume in quote.
32 ~     (),
33 |     /// Ignore.
34 ~     (),
   |

warning: `exc-binance` (lib) generated 1 warning
   Compiling examples v0.7.3-nightly (/Users/lijiachang/code/rust/exc/examples)
error[E0599]: no method named `into_fetch_candles_forward` found for struct `Exc` in the current scope
  --> examples/examples/binance_rate_limit.rs:11:10
   |
8  |       let mut binance = Binance::usd_margin_futures()
   |  _______________________-
9  | |         .connect_exc()
10 | |         .into_rate_limited(70, Duration::from_secs(60))
11 | |         .into_fetch_candles_forward(1500);  //todo method not found in `Exc<RateLimit<IntoService<Binance, Request>>, Request>`
   | |         -^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `Exc<RateLimit<IntoService<Binance, Request>>, Request>`
   | |_________|
   | 

warning: unused import: `futures::StreamExt`
 --> examples/examples/binance_rate_limit.rs:4:5
  |
4 | use futures::StreamExt;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0599`.
warning: `examples` (example "binance_rate_limit") generated 1 warning
error: could not compile `examples` (example "binance_rate_limit") due to 1 previous error; 1 warning emitted

**Comment by Nouzan** [comment]
> ➜ examples git:(main) ✗ pwd
> /Users/lijiachang/code/rust/exc/examples

Ah, I see, this is because if you run the example in this path (`exc/examples`), it will treat `examples` as a separate crate, and the `examples` crate indeed lacks some necessary features (which have just been added in #99 ) to compile.

You can try running these examples **directly from the project root** (i.e., `exc/`). Please let me know if this fixes your problem.

**Comment by lijiachang** [comment]
oh thanks，
Actually, the error went away after I updated https://github.com/Nouzan/exc/pull/99
now , i can run the example in this path (exc/examples) . it worked

fixed
